[workspace]
resolver = "2"
members = [
    "common",
    "lending_pool",
    "reserve",
    "a_token",
    "debt_token",
    "price_oracle",
    "liquidation",
]

[workspace.dependencies]
soroban-sdk = "25.0.1"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
