[package]
name = "udonfi-lending-pool"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace = true }
udonfi-common = { path = "../common" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
udonfi-a-token = { path = "../a_token" }
udonfi-debt-token = { path = "../debt_token" }
